
from typing import Dict, List, Optional, Tuple, Literal
from pydantic import BaseModel, Field, field_validator, ConfigDict
from pathlib import Path

from typing import List, Tuple, Literal, Optional
from pydantic import BaseModel, Field, ConfigDict, model_validator

#class ACISettings(BaseModel):

class DefaultGPTSettings(BaseModel):
    model: str = Field(..., description="Directory in which logs are stored")
    temperature: float = Field(..., description="Directory in which logs are stored")
    max_retries: int = Field(..., description="Directory in which logs are stored")
    gpt_log_path: str = Field(..., description="Directory in which logs are stored")
    reasoning: Dict[str, str] = Field(..., description="Reasoning parameters for certain models.")

class MemorySettings(BaseModel):
    root: str = Field(..., description="Folder in which memories are stored")
    initialize_memory: bool = Field(..., description="A new empty memory is created with memory_name")
    memory_name: str = Field(..., description="Name of the memory to be used")
    enable_tms_trim: bool = Field(
        default=True,
        description="If False, disable online short-term memory components based on TMS and TRIM.",
    )

class PlanExecutorSettings(BaseModel):
    default_pause_sec: float = Field(default=1.0, ge=0.0, description="Default pause applied to env.step() when step parameters do not specify a pause.")
    observe_after_python: bool = Field(default=True, description="If True, call env.observe() after each python step to refresh last_obs.")
    model_config = ConfigDict(extra="forbid", validate_assignment=True)

class OmniParserSettings(BaseModel):
    device: str = Field(default="cuda", description="Preferred torch device (falls back to CPU if unavailable)")
    icon_detect_model_path: str = Field(..., description="Path for the YOLO icon detector weights")

    # Captioner selection
    caption_backend: Literal["florence", "blip2"] = Field(
        default="florence",
        description="Caption model backend. 'florence' uses Florence-2, 'blip2' uses BLIP-2 captioner weights."
    )

    # Local fine-tuned weights folder (either Florence finetune or BLIP2 finetune)
    icon_caption_model_dir: str = Field(..., description="Local directory with captioner model weights and configuration")

    # Florence processor id (used when caption_backend='florence')
    icon_caption_model_id: str = Field(
        default="microsoft/Florence-2-base",
        description="HF model id for Florence-2 processor (used when caption_backend='florence')"
    )

    # BLIP-2 base id for processor (used when caption_backend='blip2')
    blip2_base_model_id: str = Field(
        default="Salesforce/blip2-opt-2.7b",
        description="HF model id for BLIP-2 base processor (used when caption_backend='blip2')"
    )

    caption_prompt: str = Field(default="<CAPTION>", description="Prompt token expected by the caption model")
    ocr_languages: List[str] = Field(default_factory=lambda: ["en"], description="EasyOCR language list for on-screen text detection")
    yolo_image_size: int = Field(default=640, description="YOLO inference image size used by ultralytics")
    box_threshold: float = Field(default=0.2, description="YOLO confidence threshold for icon detection")
    iou_threshold: float = Field(default=0.7, description="IoU threshold used by YOLO NMS and overlap filtering")
    min_icon_area_ratio: float = Field(default=1e-4, description="Discard icons smaller than this ratio of the screen area")
    max_icon_area_ratio: float = Field(default=0.3, description="Discard icons larger than this ratio of the screen area")
    icon_crop_size: Tuple[int, int] = Field(default=(64, 64), description="Size to which icon crops are resized before captioning")
    caption_max_new_tokens: int = Field(default=20, description="Maximum tokens generated by the caption model per icon")
    caption_num_beams: int = Field(default=1, description="Beam size for caption generation (1 = greedy decoding)")
    iou_eps: float = Field(default=1e-6, description="Small epsilon to avoid division by zero in IoU computation")
    default_vis_prefix: str = Field(default="omni", description="Default filename prefix for visualization images")

    model_config = ConfigDict(extra="forbid", validate_assignment=True)

    @model_validator(mode="after")
    def _validate_caption_config(self):
        # Keep it strict: enforce that BLIP2 has a base processor id
        """
        Validate caption config.
        
        Returns
        -------
        Any
            Function result.
        
        """
        if self.caption_backend == "blip2" and not self.blip2_base_model_id:
            raise ValueError("blip2_base_model_id must be set when caption_backend='blip2'")
        if self.caption_backend == "florence" and not self.icon_caption_model_id:
            raise ValueError("icon_caption_model_id must be set when caption_backend='florence'")
        return self


class AccessibilityExtractorSettings(BaseModel):
    include_invisible: bool = Field(default=True, description="Keep nodes where visible=False (when available).")
    keep_only_active_window_nodes: bool = Field(
        default=True,
        description="If True, when an app has an active frame, drop nodes from its inactive frames except state-carrying controls.",
    )
    assume_normalized_bounds: bool = Field(default=True, description="Convert [0..1]-like bounds to pixels if screen size is known.")
    clamp_bounds_to_screen: bool = Field(default=True, description="Clamp extracted bounds to the screen size when provided.")
    max_bounds_area_ratio: float = Field(default=0.95, gt=0.0, le=1.0, description="Drop bounds whose area exceeds this screen-area ratio (often bogus).")
    model_config = ConfigDict(extra="forbid", validate_assignment=True)

    @field_validator("max_bounds_area_ratio")
    @classmethod
    def _area_ratio_reasonable(cls, v: float) -> float:
        """
        Process area ratio reasonable.
        
        Parameters
        ----------
        v : float
            Function argument.
        
        Returns
        -------
        float
            Floating-point result value.
        
        """
        if v < 0.1: raise ValueError("max_bounds_area_ratio too small; use >= 0.1 unless you have a specific reason.")
        return v

class PlannerSettings(BaseModel):
    max_plan_steps: int = Field(default=50, ge=1, le=500, description="Upper bound requested to the LLM for plan length.")
    model_config = ConfigDict(extra="forbid", validate_assignment=True)


class PerceptionSettings(BaseModel):
    use_vision: bool = Field(
        default=True,
        description="If False, disable OmniParser vision branch and rely only on accessibility-tree extraction.",
    )
    debug_directory: str = Field(
        default="../data/debug/processed_screenshots",
        description="Directory used to store perception debug screenshots",
    )
    omniparser_settings: OmniParserSettings = Field(..., description="Settings for the vision extractor")
    a11y_extractor_settings: AccessibilityExtractorSettings = Field(
        default_factory=AccessibilityExtractorSettings,
        description="Settings controlling accessibility tree extraction into a structured DataFrame",
    )
    model_config = ConfigDict(extra="forbid", validate_assignment=True)

class OsworldSettings(BaseModel):
    """
    Client + environment settings for OSWorld/DesktopEnv.
    Matches the YAML structure; most fields are required, no extras allowed.
    """
    # --- environment_settings (YAML) ---
    provider_name: Literal["vmware"] = Field(..., description="Virtualization provider name")
    path_to_vm: Path = Field(..., description="Path to the .vmx file of the VMware VM")
    snapshot_name: str = Field(..., description="Snapshot name to restore (e.g., 'init_state')")
    headless: bool = Field(..., description="Run the VM without GUI")
    require_a11y_tree: bool = Field(..., description="Whether the accessibility tree is required")
    require_terminal: bool = Field(..., description="Whether a terminal is required")
    enable_proxy : bool = Field(..., description = "")
    os_type: str = Field(..., description="Guest OS type (e.g., 'Ubuntu')")
    action_space : str = Field(..., description="Action Space")
    socket_timeout_sec: float = Field(
        default=120.0,
        gt=0.0,
        description="Socket timeout (sec) used by OSWorld TCP client calls.",
    )
    init_timeout_sec: float = Field(
        default=180.0,
        gt=0.0,
        description="Maximum seconds to wait for OSWorld environment readiness at startup.",
    )
    # --- optional auth (YAML may omit) ---
    client_username: Optional[str] = Field(None, description="Username for the DesktopEnv client")
    client_password: Optional[str] = Field(None, description="Password for the DesktopEnv client")

    # --- validators ---
    @field_validator("path_to_vm", mode="before")
    @classmethod
    def validate_vmx_path(cls, v):
        """
        Validate vmx path.
        
        Parameters
        ----------
        v : Any
            Function argument.
        
        Returns
        -------
        Any
            Function result.
        
        """
        p = Path(v)
        if p.suffix.lower() != ".vmx":
            raise ValueError("path_to_vm must point to a .vmx file")
        return p

    model_config = ConfigDict(extra="forbid", validate_assignment=True)


class ExperimentConfiguration(BaseModel):
    log_dir: str = Field(..., description="Directory in which logs are stored")
    log_level: str = Field(..., description="Prefix of log messages")
    gpt_client_settings: DefaultGPTSettings = Field(..., description="Ordered chain of tasks forming the plan.")
    osworld_settings: OsworldSettings = Field(..., description="Settings for the testing environment")
    memory_settings : MemorySettings = Field(..., description="")
    perception_settings: PerceptionSettings = Field(..., description="Settings for the perception pipeline")
    plan_executor_settings: PlanExecutorSettings = Field(..., description="Settings related to the plan executor module")
    planner_settings : PlannerSettings = Field(..., description="Settings related to planner")
